version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    volumes:
      - ./backend:/app # Mount local backend code for live reload
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # This is how we pass the API URL to the Next.js build process
        # 'backend' is the service name defined above, Docker Compose handles DNS
        NEXT_PUBLIC_API_URL: http://backend:8000
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000
    volumes:
      - ./frontend:/app # Mount local frontend code
      - /app/node_modules # Prevent local node_modules from overwriting container's
      - /app/.next # Prevent local .next from overwriting container's
    depends_on:
      - backend
    environment:
      NODE_ENV: development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
